/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var l=b.document,w=b.navigator,x="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),F=!1,E=0,C=[],h=[],k=[],e=[],r={},G=0,H=[],z=null,V={},q={},ia=null,s,W=[].slice,ja,X,M,p,B,Y,N,ka,la,ma,I,Z,O,P,na,J,oa,pa,qa,ra,t,sa,D,Q,ta,$,ua,va,aa,u,wa,ba,R,S,xa,ya,T,za,ca,da,Aa,ea,A,K,L,U,fa,v=function(a){try{return{init:P,hash:O,rules:xa,
hasRules:T,defaults:Aa,__qc:function(){return!0}}[a].apply(null,W.call(arguments,1))}catch(c){return!1}};v.evts=0;v.v=2;v.SD=x;v.qpixelsent=[];S=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};da=function(a){(a=a||b._qacct)&&(aa(e,a)||e.push(a))};aa=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};ba=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};R=function(a){var c,d;c=ba(a);if("array"===c)return a.slice(0);
if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};T=function(a){return aa(k,a)};Aa=function(a,c){var d;a&&((d=V[a])&&(c=U(c,d)),c.qacct&&delete c.qacct,V[a]=c)};ea=function(a){var c,d;if(p(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?t(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=q[d])?U(c,a):a,q[d]=c);da(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ea(a[c])};U=
function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;$(d,a,c);$(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};$=function(a,c,d){var b,f,m,y,h,n;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(f=c[b],m=d[b],y="",h=!!f&&"string"==typeof f,n=!!m&&"string"==typeof m,h&&
(y=f),h&&n&&(y+=","),n&&(y+=m),a[b]=y)};A=function(){var a=[],c,d;if(!(0<G)){wa();for(c in q)q.hasOwnProperty(c)&&q[c]&&(d=q[c],a.push(d),delete q[c]);1==a.length&&t(a[0]);1<a.length&&t(a)}};K=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],T(b)||c.push(b);if(0===c.length)A();else for(d=0;d<c.length;d++)b=c[d],k.push(b),ua(b)};va=function(){for(var a;H[0]&&("loaded"==H[0].readyState||"complete"==H[0].readyState);)a=H.shift(),a.onreadystatechange=null,z.parentNode.insertBefore(a,z),L()};ua=
function(a){var c,d;c=("https:"===l.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";z=z||l.scripts[0];G++;d=l.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){r[a]=0;L()},d.onerror=function(){r[a]=1;L()},z.parentNode.insertBefore(d,z)):d.readyState?(r[a]=2,H.push(d),d.onreadystatechange=va,d.src=c):(r[a]=4,L())};L=function(){G-=0<G?1:0;A()};xa=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ea(c):t(c,!0)};for(c=0;c<arguments.length;c++)d=
W.call(arguments[c],0),d.splice(1,0,b),ya.apply(null,d);a=!1;F&&A()}};ya=function(a,c){var d=[],b=[],f=c||t,m,y,e,n,ha;if((m=W.call(arguments,2))&&m.length){y=m[0]||S;e=m[1];n=m[2];m=n.length;for(ha=0;ha<m;ha++)d.push(!1),b.push(null);d={p:a,f:d,r:y,c:n,a:e,v:b};T(a)||k.push(a);h.push(d);za(d,f)}};za=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,ga;try{b=a.c[d][0],ga=a.c[d].slice(1),ga.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;ca(a,c)}),b.apply(null,ga)}catch(h){a.f[d]=
!0,a.v[d]=!1,ca(a,c)}})(b)};ca=function(a,c){var d=a.a,b=a.v,f=a.r||S,m,h,e,n,k,g;(m=S(a.f))&&(m=m&&f(b));if(m)for(b=0;b<d.length;b++)try{h=d[b][0];e=1<d[b].length?d[b].slice(1):[];e=e.concat(a.v);n=h.apply(null,e);k={qacct:a.p,event:"rule"};for(g in n)n.hasOwnProperty(g)&&"qacct"!==g&&(k[g]=n[g]);c(k)}catch(p){}};ja=function(){return X(0)!==X(6)?1:0};X=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};M=function(a){return a.replace(/\./g,
"%2E").replace(/,/g,"%2C")};B="function"===typeof encodeURIComponent?encodeURIComponent:M;p=function(a){return"undefined"!=typeof a&&null!=a};Y=function(){return Math.round(2147483647*Math.random())};N=function(a){var c="",d=l.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};ka=function(){var a="",c=I(),d,b,f;if(1===E)return";fpan\x3du;fpa\x3d";d=O(c);for(b=0;b<x.length;b++)if(x[b]===d)return";fpan\x3du;fpa\x3d";
d=new Date;b=N("__qca");if(0<b.length){try{f=+b.split("-")[2],338688E5<d-f&&(l.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(f+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(m){}a+=";fpan\x3d0;fpa\x3d"+b}0===N("__qca").length&&(b="P0-"+Y()+"-"+d.getTime(),l.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(d.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),b=N("__qca"),a=0<b.length?a+(";fpan\x3d1;fpa\x3d"+b):a+";fpan\x3du;fpa\x3d");return a};la=function(a){l.cookie=
a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+I()};I=function(){var a,c,b,h;a=l.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");h=c.length;if(3>h)return a;b=c[h-1];return 3>b.length?a:a=c[h-2]+"."+b};Z=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};O=function(a){var c;c=Z(2166136261,a);a=Z(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};Q=function(a,c,d){var h=
"",f=b._qacct,m=null,e="webpage",k="load",n={},l,g,f=c?c.qacct||b._qacct:b._qacct;l=q[f];c?l&&(c=U(c,l)):c=l;f&&delete q[f];if(null!=c)for(g in c)n[g]=!0,c.hasOwnProperty(g)&&"string"===typeof g&&"string"===typeof c[g]&&("uid"===g||"uh"===g?(na()||(m=O(c[g])),delete c[g]):"qacct"!==g&&(h+=";"+g+a+"\x3d"+B(c[g]),"media"===g&&(e=c[g]),"event"===g&&(k=c[g])));if("string"!==typeof f){if(!p(b._qacct)||0===b._qacct.length)return"";f=b._qacct}if(f&&(l=V[f]))for(g in l)"string"===typeof g&&l.hasOwnProperty(g)&&
!n[g]&&(h+=";"+g+a+"\x3d"+B(l[g]),"media"===g&&(e=l[g]),"event"===g&&(k=l[g]));n=r[f];p(n)||(n=3);h+=";rf"+a+"\x3d"+n;"string"===typeof m&&(c.uh=m,h+=";uh"+a+"\x3d"+B(m));if("webpage"===e&&"load"===k){for(c=0;c<v.qpixelsent.length;c++)if(v.qpixelsent[c]===f&&!d)return"";v.qpixelsent.push(f)}"ad"===e&&(E=1);return";a"+a+"\x3d"+f+h};ta=function(){var a=l.getElementsByTagName("meta"),c="",b,h,f,e;for(b=0;b<a.length;b++){f=a[b];if(1E3<=c.length)return c;p(f)&&p(f.attributes)&&p(f.attributes.property)&&
p(f.attributes.property.value)&&p(f.content)&&(h=f.attributes.property.value,f=f.content,3<h.length&&"og:"===h.substring(0,3)&&(0<c.length&&(c+=","),e=80<f.length?80:f.length,c+=M(h.substring(3,h.length))+"."+M(f.substring(0,e))))}return B(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;p(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());
return a||"1"==w.doNotTrack||"yes"===w.doNotTrack||"1"==w.msDoNotTrack};t=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",h=Y(),f="",e="",k="",r="",n="",u="u",g="1",s=0,t=[],q,x,z,A;E=0;p(v.qpixelsent)||(v.qpixelsent=[]);if(p(a))for(q in a)if("string"==typeof a[q]){e=Q("",a,c);break}else"object"==typeof a[q]&&null!=a[q]&&(++s,e+=Q("."+s,a[q],c));else"string"===typeof _qacct&&(e=Q("",null,c));0!==e.length&&(s=w.cookieEnabled?"1":"0","undefined"!=typeof w.javaEnabled&&(u=w.javaEnabled()?
"1":"0"),p(b._qmeta)&&(k=";m\x3d"+B(b._qmeta),b._qmeta=null),self.screen&&(f=screen.width+"x"+screen.height+"x"+screen.colorDepth),x=new Date,z=ja(),A=ka(),b.location&&b.location.href&&(r=B(b.location.href)),l&&l.referrer&&(n=B(l.referrer)),b.self===b.top&&(g="0"),q=ta(),t.push("/pixel;r\x3d"+h+e+A+";ns\x3d"+g+";ce\x3d"+s),t.push(";je\x3d"+u+";sr\x3d"+f+";enc\x3d"+d+";dst\x3d"+z+";et\x3d"+x.getTime()+";tzo\x3d"+x.getTimezoneOffset()+k+";ref\x3d"+n+";url\x3d"+r+";ogl\x3d"+q),C.push(t),D())};sa=function(a){var c=
new Image;a=[b.location.protocol,"//pixel.",oa(s)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(s),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&la("__qca")}};D=function(){if(s)for(;C.length;)sa(C.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||p(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!p(s)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");
return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}s=1}D()};pa=function(a,c){s=PrivacyManagerAPI.callApi(a,"quantserve.com",I(),"truste.com",c);D()};qa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:I(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",J,!1);else if(b.attachEvent)b.attachEvent("onmessage",J);else{s=!0;D();return}try{b.top.postMessage(JSON.stringify(d),
"*")}catch(h){}ia=setTimeout(function(){p(s)||(s=!0,D())},25)};J=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",J,!1):b.detachEvent&&window.detachEvent("onmessage",J),s=c.PrivacyManagerAPI,D())}};fa=function(){var a=arguments,c,b;u([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],t(c);e.length?K(e.slice(0)):A()};u=function(a){var c=
ba(a);if("array"===c)for(c=0;c<a.length;c++)u(a[c]);else"object"===c&&da(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||t({qacct:b._qacct});if(!v.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&t(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&t(b.ezt[a]);b._qevents={push:fa};b.ezt.push=function(){var a=arguments,d;if(p(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else fa.apply(this,arguments)};v.evts=1}};P=
function(){var a;p(b._qevents)||(b._qevents=[]);p(b.ezt)||(b.ezt=[]);b._qoptions&&(a=R(b._qoptions),u(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=R(b.qcdata),u(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=R(b.smarttagdata),u(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);v.evts||(b._qevents.push=function(){u([].slice.call(arguments));K(e.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){u([].slice.call(arguments));K(e.slice(0));
return[].push.apply(b.ezt,arguments)});u(b.ezt);u(b._qevents);u({qacct:b._qacct});b._qoptions=null;e.length?K(e.slice(0)):A();F=!0};b.quantserve=b.quantserve||P;v.quantserve=P;return v}(window);
try{__qc("hasRules","p-UkS7f9ZMSZ6hP")||function(b,l,w){var x=function(b,k,e){return b?"nc"===b?!k||!e||0>k.indexOf(e):"eq"===b?k===e:"sw"===b?0===k.indexOf(e):"ew"===b?(b=k.length-e.length,k=k.lastIndexOf(e,b),-1!==k&&k===b):"c"===b?0<=k.indexOf(e):!1:!1},F=function(b){var k=w.createElement("a");k.href=b;return k},E=function(b,k,e){var r;r=l.top===l.self?w.location.href:F(w.referrer).href;x(k,r,e)?b(r):b(!1)},C=function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[C,"HelmStoryType.sponsored.Raygun.why-traditional-application-monitoring-tools-are-making-you-look-stupid"]],[[E,"c","/why-traditional-application-monitoring-tools-are-making-you-look-stupid"]]],[b,null,[[C,"HelmStoryType.sponsored.WellsFargo"]],[[function(b,k,e){var r;r=l.top===l.self?w.location.pathname:F(w.referrer).pathname;x(k,r,e)?b(r):b(!1)},"eq","/2017/02/01/friend-or-foe-why-fintech-and-banks-need-each-other/"]]],[b,null,[[C,"HelmStoryType.sponsored.WellsFargo.20170228"]],
[[E,"c","/when-banks-and-fintech-innovate-together-consumers-win"]]])}("p-UkS7f9ZMSZ6hP",window,document)}catch(nfe$$3){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$4){};